/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated.historico'
import { Route as AuthenticatedGruposRouteImport } from './routes/_authenticated.grupos'
import { Route as AuthenticatedDisparoRouteImport } from './routes/_authenticated.disparo'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated.configuracoes'
import { Route as AuthenticatedConexoesRouteImport } from './routes/_authenticated.conexoes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedListasIndexRouteImport } from './routes/_authenticated.listas.index'
import { Route as AuthenticatedListasIdRouteImport } from './routes/_authenticated.listas.$id'
import { Route as AuthenticatedHistoricoIdRouteImport } from './routes/_authenticated.historico.$id'
import { Route as ApiPublicHooksDisparoTickRouteImport } from './routes/api/public/hooks/disparo-tick'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGruposRoute = AuthenticatedGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDisparoRoute = AuthenticatedDisparoRouteImport.update({
  id: '/disparo',
  path: '/disparo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConexoesRoute = AuthenticatedConexoesRouteImport.update({
  id: '/conexoes',
  path: '/conexoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedListasIndexRoute =
  AuthenticatedListasIndexRouteImport.update({
    id: '/listas/',
    path: '/listas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedListasIdRoute = AuthenticatedListasIdRouteImport.update({
  id: '/listas/$id',
  path: '/listas/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoricoIdRoute =
  AuthenticatedHistoricoIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedHistoricoRoute,
  } as any)
const ApiPublicHooksDisparoTickRoute =
  ApiPublicHooksDisparoTickRouteImport.update({
    id: '/api/public/hooks/disparo-tick',
    path: '/api/public/hooks/disparo-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/conexoes': typeof AuthenticatedConexoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/disparo': typeof AuthenticatedDisparoRoute
  '/grupos': typeof AuthenticatedGruposRoute
  '/historico': typeof AuthenticatedHistoricoRouteWithChildren
  '/historico/$id': typeof AuthenticatedHistoricoIdRoute
  '/listas/$id': typeof AuthenticatedListasIdRoute
  '/listas/': typeof AuthenticatedListasIndexRoute
  '/api/public/hooks/disparo-tick': typeof ApiPublicHooksDisparoTickRoute
}
export interface FileRoutesByTo {
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/conexoes': typeof AuthenticatedConexoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/disparo': typeof AuthenticatedDisparoRoute
  '/grupos': typeof AuthenticatedGruposRoute
  '/historico': typeof AuthenticatedHistoricoRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/historico/$id': typeof AuthenticatedHistoricoIdRoute
  '/listas/$id': typeof AuthenticatedListasIdRoute
  '/listas': typeof AuthenticatedListasIndexRoute
  '/api/public/hooks/disparo-tick': typeof ApiPublicHooksDisparoTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/conexoes': typeof AuthenticatedConexoesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/disparo': typeof AuthenticatedDisparoRoute
  '/_authenticated/grupos': typeof AuthenticatedGruposRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/historico/$id': typeof AuthenticatedHistoricoIdRoute
  '/_authenticated/listas/$id': typeof AuthenticatedListasIdRoute
  '/_authenticated/listas/': typeof AuthenticatedListasIndexRoute
  '/api/public/hooks/disparo-tick': typeof ApiPublicHooksDisparoTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/admin'
    | '/conexoes'
    | '/configuracoes'
    | '/disparo'
    | '/grupos'
    | '/historico'
    | '/historico/$id'
    | '/listas/$id'
    | '/listas/'
    | '/api/public/hooks/disparo-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cadastro'
    | '/login'
    | '/admin'
    | '/conexoes'
    | '/configuracoes'
    | '/disparo'
    | '/grupos'
    | '/historico'
    | '/'
    | '/historico/$id'
    | '/listas/$id'
    | '/listas'
    | '/api/public/hooks/disparo-tick'
  id:
    | '__root__'
    | '/_authenticated'
    | '/cadastro'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/conexoes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/disparo'
    | '/_authenticated/grupos'
    | '/_authenticated/historico'
    | '/_authenticated/'
    | '/_authenticated/historico/$id'
    | '/_authenticated/listas/$id'
    | '/_authenticated/listas/'
    | '/api/public/hooks/disparo-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  ApiPublicHooksDisparoTickRoute: typeof ApiPublicHooksDisparoTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grupos': {
      id: '/_authenticated/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof AuthenticatedGruposRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/disparo': {
      id: '/_authenticated/disparo'
      path: '/disparo'
      fullPath: '/disparo'
      preLoaderRoute: typeof AuthenticatedDisparoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conexoes': {
      id: '/_authenticated/conexoes'
      path: '/conexoes'
      fullPath: '/conexoes'
      preLoaderRoute: typeof AuthenticatedConexoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/listas/': {
      id: '/_authenticated/listas/'
      path: '/listas'
      fullPath: '/listas/'
      preLoaderRoute: typeof AuthenticatedListasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/listas/$id': {
      id: '/_authenticated/listas/$id'
      path: '/listas/$id'
      fullPath: '/listas/$id'
      preLoaderRoute: typeof AuthenticatedListasIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historico/$id': {
      id: '/_authenticated/historico/$id'
      path: '/$id'
      fullPath: '/historico/$id'
      preLoaderRoute: typeof AuthenticatedHistoricoIdRouteImport
      parentRoute: typeof AuthenticatedHistoricoRoute
    }
    '/api/public/hooks/disparo-tick': {
      id: '/api/public/hooks/disparo-tick'
      path: '/api/public/hooks/disparo-tick'
      fullPath: '/api/public/hooks/disparo-tick'
      preLoaderRoute: typeof ApiPublicHooksDisparoTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedHistoricoRouteChildren {
  AuthenticatedHistoricoIdRoute: typeof AuthenticatedHistoricoIdRoute
}

const AuthenticatedHistoricoRouteChildren: AuthenticatedHistoricoRouteChildren =
  {
    AuthenticatedHistoricoIdRoute: AuthenticatedHistoricoIdRoute,
  }

const AuthenticatedHistoricoRouteWithChildren =
  AuthenticatedHistoricoRoute._addFileChildren(
    AuthenticatedHistoricoRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedConexoesRoute: typeof AuthenticatedConexoesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDisparoRoute: typeof AuthenticatedDisparoRoute
  AuthenticatedGruposRoute: typeof AuthenticatedGruposRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedListasIdRoute: typeof AuthenticatedListasIdRoute
  AuthenticatedListasIndexRoute: typeof AuthenticatedListasIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedConexoesRoute: AuthenticatedConexoesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDisparoRoute: AuthenticatedDisparoRoute,
  AuthenticatedGruposRoute: AuthenticatedGruposRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedListasIdRoute: AuthenticatedListasIdRoute,
  AuthenticatedListasIndexRoute: AuthenticatedListasIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  ApiPublicHooksDisparoTickRoute: ApiPublicHooksDisparoTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
